/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formularios;

import java.awt.Color;
import java.util.Random;
import javafx.scene.layout.Background;
import javax.swing.*;

/**
 *
 * @author Cristian
 */
public class form1 extends javax.swing.JFrame {

    /**
     * Creates new form form1
     */
    public form1() {
        initComponents();

        this.getContentPane().setBackground(Color.orange);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        jDialog2 = new javax.swing.JDialog();
        jToggleButton1 = new javax.swing.JToggleButton();
        jTextField1 = new javax.swing.JTextField();
        p1 = new javax.swing.JLabel();
        p2 = new javax.swing.JLabel();
        p3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        sel = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jDialog2Layout = new javax.swing.GroupLayout(jDialog2.getContentPane());
        jDialog2.getContentPane().setLayout(jDialog2Layout);
        jDialog2Layout.setHorizontalGroup(
            jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog2Layout.setVerticalGroup(
            jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        jToggleButton1.setText("jToggleButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tragamonedas DaVinci");
        setBackground(new java.awt.Color(0, 0, 0));
        setLocation(new java.awt.Point(400, 300));

        jTextField1.setEditable(false);
        jTextField1.setBackground(new java.awt.Color(255, 204, 204));
        jTextField1.setFont(new java.awt.Font("Arial", 0, 48)); // NOI18N
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField1.setText("100");
        jTextField1.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(255, 204, 204), new java.awt.Color(255, 204, 204)));
        jTextField1.setFocusable(false);
        jTextField1.setOpaque(false);
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        p1.setBackground(new java.awt.Color(255, 255, 255));
        p1.setMaximumSize(new java.awt.Dimension(165, 165));
        p1.setMinimumSize(new java.awt.Dimension(165, 165));
        p1.setPreferredSize(new java.awt.Dimension(165, 165));

        p2.setBackground(new java.awt.Color(255, 255, 255));
        p2.setMaximumSize(new java.awt.Dimension(165, 165));
        p2.setMinimumSize(new java.awt.Dimension(165, 165));
        p2.setPreferredSize(new java.awt.Dimension(165, 165));

        p3.setBackground(new java.awt.Color(255, 255, 255));
        p3.setMaximumSize(new java.awt.Dimension(165, 165));
        p3.setMinimumSize(new java.awt.Dimension(165, 165));
        p3.setPreferredSize(new java.awt.Dimension(165, 165));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/giphy-1 - unscreen.gif"))); // NOI18N

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondo_png_con_nieve__by_baastysmiler_d4moevp-fullview.png"))); // NOI18N
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Yu Gothic Medium", 1, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Apuesta");

        jLabel3.setFont(new java.awt.Font("Yu Gothic", 3, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 51));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("¡Apuesta para ganar!");
        jLabel3.setToolTipText("");

        jButton3.setText("Retirar");
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        sel.setFont(new java.awt.Font("Yu Gothic Medium", 0, 18)); // NOI18N
        sel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "20", "40", "100", "500", "1000" }));
        sel.setToolTipText("");
        sel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        sel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selActionPerformed(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/reset (2).png"))); // NOI18N
        jButton2.setBorderPainted(false);
        jButton2.setContentAreaFilled(false);
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton4.setText("Menu");
        jButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondo_tragamonedas (2).jpg"))); // NOI18N
        jLabel4.setPreferredSize(new java.awt.Dimension(738, 446));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/mano.png"))); // NOI18N
        jLabel5.setText("jLabel5");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(230, 230, 230)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 474, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(124, 124, 124)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(190, 190, 190)
                .addComponent(p1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(p2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(p3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(125, 125, 125)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(860, 860, 860)
                .addComponent(sel, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(320, 320, 320)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(360, 360, 360)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(360, 360, 360)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 1000, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel5))))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(p1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(p2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(p3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(5, 5, 5)
                .addComponent(sel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(90, 90, 90)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton4)
                                .addGap(7, 7, 7)
                                .addComponent(jButton3))
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))))
            .addGroup(layout.createSequentialGroup()
                .addGap(500, 500, 500)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 605, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed

    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        Random rnd = new Random();
        int Dis, Ap, rpa1, rpa2, rpa3, Fin = 0;
        int[] panels = new int[3];

        Dis = Integer.parseInt(jTextField1.getText());
        Ap = Integer.parseInt(sel.getSelectedItem().toString());

        p1.setVisible(true);
        p2.setVisible(true);
        p3.setVisible(true);

        if (Ap > Dis || Ap < 0) {
            jLabel3.setText("No tenés suficiente dinero");
        }

        for (int i = 0; i < panels.length; i++) {
            panels[i] = rnd.nextInt(5);
        }

        jButton2.setVisible(false);

        if (Dis >= 20 && Ap <= Dis) {

            for (int i = 0; i < panels.length; i++) {
                switch (panels[i]) {
                    case 0:
                        if (i == 0) {
                            p1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cerezas.png")));
                        } else if (i == 1) {
                            p2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cerezas.png")));
                        } else if (i == 2) {
                            p3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cerezas.png")));
                        }
                        break;
                    case 1:
                        if (i == 0) {
                            p1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/7.png")));
                        } else if (i == 1) {
                            p2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/7.png")));
                        } else if (i == 2) {
                            p3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/7.png")));
                        }
                        break;
                    case 2:
                        if (i == 0) {
                            p1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/sandia.png")));
                        } else if (i == 1) {
                            p2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/sandia.png")));
                        } else if (i == 2) {
                            p3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/sandia.png")));
                        }
                        break;
                    case 3:
                        if (i == 0) {
                            p1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/uvas.png")));
                        } else if (i == 1) {
                            p2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/uvas.png")));
                        } else if (i == 2) {
                            p3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/uvas.png")));
                        }
                        break;
                    case 4:
                        if (i == 0) {
                            p1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/limon.png")));
                        } else if (i == 1) {
                            p2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/limon.png")));
                        } else if (i == 2) {
                            p3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/limon.png")));
                        }
                        break;
                }
            }

            jLabel3.setText("Perdiste $" + Ap);

            if (panels[1] == panels[2] && panels[0] == panels[1]) {

                Dis += Ap * 2;
                jLabel3.setText("Ganaste $" + Ap * 3);
            } else if (panels[0] == panels[1] || panels[0] == panels[2] || panels[2] == panels[1]) {
                Dis += (Ap / 2);
                jLabel3.setText("Recuperaste $" + (Ap / 2));
            } else {
                Dis -= Ap;
            }

        } else if (Dis < 20) {
            jLabel3.setText("No tienes fondos suficientes");
            p1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/game_over_1.png")));
            p2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/game_over_2.png")));
            p3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/game_over_3.png")));

        }

        jTextField1.setText(String.valueOf(Dis));

        Fin = Integer.parseInt(jTextField1.getText());

        if (Fin < 20) {
            jLabel3.setText("Perdiste");
            jButton2.setVisible(true);

            jTextField1.setText("0");
            p1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/game_over_1.png")));
            p2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/game_over_2.png")));
            p3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/game_over_3.png")));
        }


    }//GEN-LAST:event_jButton1ActionPerformed

    private void selActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_selActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        int Dis;

        Dis = Integer.parseInt(jTextField1.getText());

        if (Dis < 20) {
            jTextField1.setText("100");
            jLabel3.setText("Has reiniciado");
            p1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/null.png")));
            p2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/null.png")));
            p3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/null.png")));
        }


    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        int Dis;

        Dis = Integer.parseInt(jTextField1.getText());

        jLabel3.setText("Has retirado: " + Dis);

        jTextField1.setText("0");


    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        form2 f2 = new form2();
        f2.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(form1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(form1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(form1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(form1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new form1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JDialog jDialog2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JLabel p1;
    private javax.swing.JLabel p2;
    private javax.swing.JLabel p3;
    private javax.swing.JComboBox<String> sel;
    // End of variables declaration//GEN-END:variables
}
